rp.endpoint=http://10.142.52.96:8080/
rp.uuid=bf98ec86-8df9-4467-97a5-3682f0f5a34f
#rp.launch=
rp.project=payments
#rp.enable=
#rp.description=
#rp.attributes=
#rp.rerun=
#rp.rerun.of=
rp.retry=true
generate.failed.xml=true