#Mock Webpay url
ICICI_UPI_WEB_PAY_URL=https://pgp-automation.paytm.in/mockbank/api/MerchantAPI/UPI/v2/CollectPay
ICICI_NB_WEB_PAY_URL=https://pgp-automation.paytm.in/mockbank/bankFormatter/iciciFormatter/request1.jsp
PAYTMCC_WEB_PAY_URL="https://pgp-automation.paytm.in/mockank/digitalcredit/transact


#Mock status Query urls
ICICI_UPI_STATUS_QRY_URL=https://pgp-automation.paytm.in/mockbank/api/MerchantAPI/UPI/v2/TransactionStatus
ICICI_NB_STATUS_QRY_URL=https://pgp-automation.paytm.in/mockbank/corp/BANKAWAY?IWQRYTASKOBJNAME=bay_mc_login&BAY_BANKID=ICI
PAYTMCC_STATUS_QRY_URL=https://pgp-automation.paytm.in/mockbank/digitalcredit/v2/user/checkBalance


#Mock refund urls
ICICI_UPI_REFUND_URL=https://pgp-automation.paytm.in/mockbank/api/MerchantAPI/UPI/v1/Refund/125004

#Mock Webresponse urls
HDFC_WEB_RESPONSE=/instaproxy/bankresponse/HDFC/CC
ICICI_WEB_RESPONSE_URL=/instaproxy/bankresponse/ICICI/CC
