package scripts.api.theia

import org.testng.annotations.Test

interface AccessAuthenticationTest {
    @Test
    void 'test when head token equals access token generated by different merchant'()

    @Test
    void 'test when head token equals access token generated for OFFUS user'()

    @Test
    void 'test when head token equals access token generated for ONUS user'()
}