#!/usr/bin/env python3
# AI-Generated: 2025-01-14 - Pre-commit hook for AI code detection and tracking
"""
Pre-commit hook to detect AI-generated code and track usage statistics.
This script runs automatically before each commit to scan staged files.
"""

import os
import re
import sys
import json
import datetime
from pathlib import Path
from collections import defaultdict

# Configuration
AI_TRACKING_FILE = '.ai_tracking.log'
AI_STATS_FILE = '.ai_stats.json'
REQUIRED_AI_MARKER = False  # Set to True if you want to require AI markers

# File extensions to scan
CODE_EXTENSIONS = {
    '.py', '.js', '.ts', '.jsx', '.tsx', '.java', '.cpp', '.c', '.h', 
    '.hpp', '.cs', '.php', '.rb', '.go', '.rs', '.swift', '.kt', '.scala',
    '.html', '.css', '.scss', '.sass', '.less', '.vue', '.svelte'
}

# AI detection patterns (in order of confidence)
AI_PATTERNS = {
    'high_confidence': [
        # Cursor-specific patterns
        r'// Generated by Cursor',
        r'# Generated by Cursor',
        r'<!-- Generated by Cursor -->',
        r'/\* Generated by Cursor \*/',
        
        # Standard AI markers
        r'// AI-Generated:',
        r'# AI-Generated:',
        r'<!-- AI-Generated: -->',
        r'/\* AI-Generated: \*/',
        
        # Cursor's internal patterns
        r'cursor_',
        r'__cursor__',
    ],
    
    'medium_confidence': [
        # AI generation indicators
        r'// TODO: Review AI-generated code',
        r'# TODO: Review AI-generated code',
        r'// FIXME: AI-generated - verify logic',
        r'# FIXME: AI-generated - verify logic',
        
        # Common AI patterns
        r'// Generated by AI',
        r'# Generated by AI',
        r'// AI assisted',
        r'# AI assisted',
    ],
    
    'low_confidence': [
        # Suspicious patterns that might indicate AI generation
        r'// Auto-generated',
        r'# Auto-generated',
        r'// Generated code',
        r'# Generated code',
    ]
}

def get_git_info():
    """Get current Git repository information"""
    try:
        repo_path = os.popen('git rev-parse --show-toplevel').read().strip()
        current_branch = os.popen('git branch --show-current').read().strip()
        commit_hash = os.popen('git rev-parse HEAD').read().strip()
        return repo_path, current_branch, commit_hash
    except Exception as e:
        print(f"❌ Error getting Git info: {e}")
        return None, None, None

def get_staged_files():
    """Get list of staged files that will be committed"""
    try:
        staged_files = os.popen('git diff --cached --name-only').read().strip()
        if not staged_files:
            return []
        return [f.strip() for f in staged_files.split('\n') if f.strip()]
    except Exception as e:
        print(f"❌ Error getting staged files: {e}")
        return []

def detect_ai_patterns(file_path):
    """Detect AI-generated code patterns in a file"""
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        results = {
            'high_confidence': [],
            'medium_confidence': [],
            'low_confidence': [],
            'total_matches': 0
        }
        
        for confidence_level, patterns in AI_PATTERNS.items():
            for pattern in patterns:
                matches = re.findall(pattern, content, re.IGNORECASE)
                if matches:
                    results[confidence_level].append({
                        'pattern': pattern,
                        'count': len(matches),
                        'matches': matches[:3]  # Limit to first 3 matches
                    })
                    results['total_matches'] += len(matches)
        
        return results
    except Exception as e:
        print(f"⚠️ Warning: Could not read {file_path}: {e}")
        return None

def calculate_ai_score(detection_results):
    """Calculate AI generation likelihood score (0-100)"""
    if not detection_results:
        return 0
    
    score = 0
    # Fix: Count the actual pattern matches, not the length of the results
    score += len(detection_results['high_confidence']) * 10
    score += len(detection_results['medium_confidence']) * 5
    score += len(detection_results['low_confidence']) * 2
    
    # Cap at 100
    return min(score, 100)

def analyze_staged_files():
    """Analyze all staged files for AI-generated code"""
    staged_files = get_staged_files()
    if not staged_files:
        print("ℹ️ No staged files to analyze")
        return None, None
    
    ai_generated_files = []
    total_files = 0
    file_analysis = {}
    
    for file_path in staged_files:
        # Only analyze code files
        if not any(file_path.endswith(ext) for ext in CODE_EXTENSIONS):
            continue
        
        if not os.path.exists(file_path):
            continue
        
        total_files += 1
        detection_results = detect_ai_patterns(file_path)
        
        if detection_results and detection_results['total_matches'] > 0:
            ai_score = calculate_ai_score(detection_results)
            file_analysis[file_path] = {
                'ai_score': ai_score,
                'detection_results': detection_results,
                'is_ai_generated': ai_score >= 30  # Threshold for AI generation
            }
            
            if ai_score >= 30:
                ai_generated_files.append(file_path)
    
    return file_analysis, total_files

def log_ai_usage(file_analysis, total_files):
    """Log AI usage statistics"""
    timestamp = datetime.datetime.now().isoformat()
    repo_path, current_branch, commit_hash = get_git_info()
    
    # Calculate statistics
    ai_files = [f for f, analysis in file_analysis.items() if analysis['is_ai_generated']]
    ai_percentage = (len(ai_files) / total_files * 100) if total_files > 0 else 0
    
    # Log to tracking file
    log_entry = {
        'timestamp': timestamp,
        'commit_hash': commit_hash,
        'branch': current_branch,
        'total_files': total_files,
        'ai_files': len(ai_files),
        'ai_percentage': round(ai_percentage, 2),
        'files': file_analysis
    }
    
    # Append to tracking log
    with open(AI_TRACKING_FILE, 'a') as f:
        f.write(json.dumps(log_entry) + '\n')
    
    # Update stats file
    update_stats_file(log_entry)
    
    return ai_percentage, len(ai_files)

def update_stats_file(log_entry):
    """Update cumulative statistics file"""
    stats_file = AI_STATS_FILE
    stats = {}
    
    if os.path.exists(stats_file):
        try:
            with open(stats_file, 'r') as f:
                stats = json.load(f)
        except:
            stats = {}
    
    # Initialize if needed
    if 'commits' not in stats:
        stats['commits'] = []
    if 'summary' not in stats:
        stats['summary'] = {
            'total_commits': 0,
            'total_files': 0,
            'total_ai_files': 0,
            'average_ai_percentage': 0
        }
    
    # Add current commit
    stats['commits'].append(log_entry)
    stats['summary']['total_commits'] += 1
    stats['summary']['total_files'] += log_entry['total_files']
    stats['summary']['total_ai_files'] += log_entry['ai_files']
    
    # Calculate average
    if stats['summary']['total_commits'] > 0 and stats['summary']['total_files'] > 0:
        stats['summary']['average_ai_percentage'] = round(
            (stats['summary']['total_ai_files'] / stats['summary']['total_files']) * 100, 2
        )
    
    # Keep only last 100 commits to avoid huge files
    if len(stats['commits']) > 100:
        stats['commits'] = stats['commits'][-100:]
    
    # Save updated stats
    with open(stats_file, 'w') as f:
        json.dump(stats, f, indent=2)

def display_results(file_analysis, total_files, ai_percentage, ai_file_count):
    """Display analysis results to the user"""
    print("\n" + "="*60)
    print("🤖 AI-GENERATED CODE DETECTION RESULTS")
    print("="*60)
    
    if total_files == 0:
        print("ℹ️ No code files staged for commit")
        return
    
    print(f"📊 Summary:")
    print(f"   Total files analyzed: {total_files}")
    print(f"   Files with AI indicators: {ai_file_count}")
    print(f"   AI-generated code percentage: {ai_percentage:.1f}%")
    
    if ai_file_count > 0:
        print(f"\n🔍 AI-Generated Files:")
        for file_path, analysis in file_analysis.items():
            if analysis['is_ai_generated']:
                score = analysis['ai_score']
                print(f"   🤖 {file_path} (Score: {score}%)")
                
                # Show detection details
                for confidence_level, patterns in analysis['detection_results'].items():
                    if patterns and isinstance(patterns, list):
                        print(f"      {confidence_level}: {len(patterns)} patterns found")
                    elif patterns and isinstance(patterns, dict):
                        # Handle case where patterns might be structured differently
                        pattern_count = len(patterns) if isinstance(patterns, (list, dict)) else 0
                        print(f"      {confidence_level}: {pattern_count} patterns found")
    
    print(f"\n📈 Statistics logged to: {AI_TRACKING_FILE}")
    print(f"📊 Cumulative stats: {AI_STATS_FILE}")
    print("="*60)

def main():
    """Main pre-commit hook function"""
    print("🔍 Running AI code detection pre-commit hook...")
    
    # Check if we're in a Git repository
    if not os.path.exists('.git'):
        print("❌ Not in a Git repository. Skipping AI detection.")
        return 0
    
    # Analyze staged files
    file_analysis, total_files = analyze_staged_files()
    
    if file_analysis is None:
        print("ℹ️ No analysis performed")
        return 0
    
    # Log results
    ai_percentage, ai_file_count = log_ai_usage(file_analysis, total_files)
    
    # Display results
    display_results(file_analysis, total_files, ai_percentage, ai_file_count)
    
    # Optional: Block commits if AI markers are required but missing
    if REQUIRED_AI_MARKER and ai_file_count > 0:
        print("\n⚠️ WARNING: AI-generated code detected without proper markers!")
        print("   Consider adding AI-Generated comments to these files.")
        print("   Commit will proceed, but please review the flagged files.")
    
    print("\n✅ Pre-commit hook completed successfully")
    return 0

if __name__ == "__main__":
    sys.exit(main()) 